version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2
  cutie-shell-buildd: cutie-shell/cutie-shell-buildd-orb@volatile

jobs:
  setup:
    executor: continuation/default
    resource_class: small
    steps:
      - checkout
      - cutie-shell-buildd/generate
      - continuation/continue:
          configuration_path: generated_config.yml

workflows:
  setup:
    jobs:
      - setup:
          filters:
            tags:
              only: /^cutie\/.*\/.*/
