version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2
  eriki73-debs-buildd: eriki73-debs/eriki73-debs-buildd-orb@volatile

jobs:
  setup:
    executor: continuation/default
    resource_class: small
    steps:
      - checkout
      - eriki73-debs-buildd/generate
      - continuation/continue:
          configuration_path: generated_config.yml

workflows:
  setup:
    jobs:
      - setup:
          filters:
            tags:
              only: /^cutie\/.*\/.*/
