// SPDX-FileCopyrightText: 2026 Cutie Shell Contributors
// SPDX-License-Identifier: GPL-3.0-or-later

#ifndef INPUT_EVENTS_H
#define INPUT_EVENTS_H

#include <QPointF>
#include <Qt>
#include <QString>

/**
 * @brief Type of pointer event
 */
enum class PointerEventType {
	Press, ///< Mouse button pressed
	Release, ///< Mouse button released
	Move ///< Mouse moved
};

/**
 * @brief Type of keyboard event
 */
enum class KeyEventType {
	Press, ///< Key pressed
	Release ///< Key released
};

/**
 * @brief Pointer (mouse) event data
 * 
 * Contains all information about a pointer event including position,
 * button state, and keyboard modifiers.
 */
struct PointerEvent {
	QPointF globalPosition; ///< Position in global compositor coordinates
	Qt::MouseButton button; ///< Button that triggered the event
	Qt::MouseButtons buttons; ///< Current state of all buttons
	Qt::KeyboardModifiers
		modifiers; ///< Active keyboard modifiers (Ctrl, Shift, etc.)
	PointerEventType type; ///< Type of pointer event
};

/**
 * @brief Keyboard event data
 * 
 * Contains all information about a keyboard event including the key code,
 * modifiers, and resulting text.
 */
struct KeyboardEvent {
	quint32 nativeScanCode; ///< Platform-specific scan code
	Qt::Key key; ///< Qt key code
	Qt::KeyboardModifiers modifiers; ///< Active keyboard modifiers
	QString text; ///< Text generated by the key press
	KeyEventType type; ///< Type of keyboard event
};

#endif // INPUT_EVENTS_H
